name: auth

services:
  auth-postgres:
    image: postgres:16.1
    restart: always
    env_file: 
      - "./core/.env"
    ports:
      - "5433:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data

  auth-redis:
    image: redis:7.2.5
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - auth-redis-data:/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 60s
      retries: 5

  auth-postgres-test:
    image: postgres:16.1
    restart: always
    env_file:
      - "./core/.env"
    ports:
      - "5434:5433"
  
  ms-auth:
    build:
      context: .
    env_file: 
      - "./core/.env"
    depends_on:
      - auth-postgres
      - auth-redis
    restart: always
    command: uvicorn main:app --host=0.0.0.0 --port=8000
  
volumes:
  auth-postgres-data:
    driver: local
  auth-redis-data:
    driver: local